name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.3"
      - name: Swift Version
        run: swift --version
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
